version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - ../../storage/mongo:/data/db
  server:
    container_name: server
    restart: always
    build:
      dockerfile: ../Docker/dev/Dockerfile
      context: ../../server
    ports:
      - '8999:8999'
    volumes:
      - ../../server:/usr/src/app
    links:
      - mongo

volumes:
  mongo-data:
