version: '3'
services:
  rents_analyzer_mongo:
    container_name: rents_analyzer_mongo
    image: mongo:4.4
    logging:
      driver: none
    ports:
      - '27017:27017'
    volumes:
      - ../../storage/mongo:/data/db
  rents_analyzer_server:
    container_name: rents_analyzer_server
    restart: always
    build:
      dockerfile: ../Docker/dev/Dockerfile
      context: ../../server
    ports:
      - '8999:8999'
    volumes:
      - ../../server:/usr/src/app
      - /usr/src/app/node_modules/
    links:
      - rents_analyzer_mongo

volumes:
  mongo-data:
